// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owygscphklgvbygohjbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93eWdzY3Boa2xndmJ5Z29oamJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTY1NDgsImV4cCI6MjA1OTYzMjU0OH0.uNieDuSRsZ4Eosfh8bIFzGt_qXQ8TsquRf_mZ8EDa1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);